export const FETCH_PURCHASE_START = 'FETCH_PURCHASE_START';
export const FETCH_PURCHASE_SUCCESS = 'FETCH_PURCHASE_SUCCESS';
export const FETCH_PURCHASE_FAILURE = 'FETCH_PURCHASE_FAILURE';

export const ADD_PURCHASE_START = 'ADD_PURCHASE_START';
export const ADD_PURCHASE_SUCCESS = 'ADD_PURCHASE_SUCCESS';
export const ADD_PURCHASE_FAILURE = 'ADD_PURCHASE_FAILURE';

export const UPDATE_PURCHASE_START = 'UPDATE_PURCHASE_START';
export const UPDATE_PURCHASE_SUCCESS = 'UPDATE_PURCHASE_SUCCESS';
export const UPDATE_PURCHASE_FAILURE = 'UPDATE_PURCHASE_FAILURE';

export const DELETE_PURCHASE_START = 'DELETE_PURCHASE_START';
export const DELETE_PURCHASE_SUCCESS = 'DELETE_PURCHASE_SUCCESS';
export const DELETE_PURCHASE_FAILURE = 'DELETE_PURCHASE_FAILURE';
